ALTER TABLE tbl_department
    ALTER COLUMN department_id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE tbl_employee
    ALTER COLUMN employee_id ADD GENERATED BY DEFAULT AS IDENTITY,
    ALTER COLUMN dob TYPE date USING NULLIF(TRIM(dob), '')::date,
    ALTER COLUMN status TYPE varchar(20) USING 'ACTIVE',
    ALTER COLUMN status SET DEFAULT 'ACTIVE',
    ALTER COLUMN status SET NOT NULL;

ALTER TABLE tbl_leave
    ALTER COLUMN leave_id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE tbl_attendance
    ALTER COLUMN attendance_id ADD GENERATED BY DEFAULT AS IDENTITY,
    ADD COLUMN status varchar(20) NOT NULL DEFAULT 'PRESENT',
    ADD CONSTRAINT chk_tbl_attendance_status
        CHECK (status IN ('PRESENT', 'LATE', 'ABSENT')),
    ADD CONSTRAINT uq_tbl_attendance_employee_date
        UNIQUE (employee_id, attendance_date);

CREATE TABLE tbl_attendance_correction_audit (
    correction_audit_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attendance_id integer NOT NULL,
    corrected_by integer NOT NULL,
    correction_reason varchar(500) NOT NULL,
    previous_check_in timestamp without time zone,
    previous_check_out timestamp without time zone,
    previous_late_minutes integer,
    previous_status varchar(20),
    corrected_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_tbl_attendance_correction_audit_attendance
        FOREIGN KEY (attendance_id) REFERENCES tbl_attendance(attendance_id),
    CONSTRAINT fk_tbl_attendance_correction_audit_corrected_by
        FOREIGN KEY (corrected_by) REFERENCES tbl_employee(employee_id),
    CONSTRAINT chk_tbl_attendance_correction_audit_reason
        CHECK (char_length(TRIM(correction_reason)) > 0)
);
