CREATE TABLE tbl_payroll_profile (
    profile_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id integer NOT NULL UNIQUE,
    base_salary numeric(10, 2) NOT NULL,
    daily_rate numeric(10, 2) NOT NULL,
    late_penalty_per_minute numeric(10, 2) NOT NULL,
    CONSTRAINT fk_tbl_payroll_profile_employee FOREIGN KEY (employee_id) REFERENCES tbl_employee (employee_id)
);

CREATE TABLE tbl_payroll_record (
    payroll_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id integer NOT NULL,
    period date NOT NULL,
    generated_date date NOT NULL,
    base_salary numeric(10, 2) NOT NULL,
    total_late_minutes integer NOT NULL,
    late_deduction numeric(10, 2) NOT NULL,
    unpaid_leave_days integer NOT NULL,
    unpaid_leave_deduction numeric(10, 2) NOT NULL,
    net_salary numeric(10, 2) NOT NULL,
    CONSTRAINT fk_tbl_payroll_record_employee FOREIGN KEY (employee_id) REFERENCES tbl_employee (employee_id)
);
